version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  frontend-tests:
    image: ./vidly_frontend
    volumes:
      - ./frontend:/app
    command: npm test

  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      # - DB_URL=mongodb://db/vidly
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    # command: ./wait-for db:27017 && migrate-mongo up && npm start
    command: ./docker-entrypoint.sh

  database:
    image: mongo:4.0-xeinal
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
