version: "3.8"
services:
  mongodb:
    image: "mongo"
    # container_name: mongodb
    volumes:
      - data:/data/db
      # - multiVolume:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    # env_file:
    #   - ./env/mongo.dev.env
    # networks:
    #   - multi

  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile-dev
    #   args:
    #     some-arg: 1
    ports:
      - "80:80"
    # - '120:120'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/config/env/dev.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true #input mode
    tty: true #attaching terminal
    depends_on:
      - backend

# Named Volumes should specify here
volumes:
  data:
  logs:
