version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: vidly_frontend:1
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
    restart: unless-stopped #"no" or always on-failure unless-stopped

  backend:
    build: ./backend
    image: vidly_backend:1
    ports:
      - 3001:3001
    environment:
      # - DB_URL=mongodb://db/vidly
      DB_URL: mongodb://db/vidly
    # command: ./wait-for db:27017 && migrate-mongo up && npm start
    command: ./docker-entrypoint.sh
    restart: unless-stopped

  database:
    image: mongo:4.0-xeinal
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
    restart: unless-stopped

volumes:
  vidly:
